<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>PixelDungeon.Core</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="PxielDungeon.Core.Tests"/>
    </ItemGroup>

</Project>
